### ISSUE TITLE
After accepting cookies, refresh page and the cookie bar appears for a second

### ISSUE THREAD

**Issue by dangelion** [carlwoodhouse/jquery.cookieBar#11]
As the title.
I see this bug also on the demo page: http://carlwoodhouse.github.io/jquery.cookieBar/

How can solve?

**Comment by carlwoodhouse** [comment]
are you using it on an existing div or letting cookiebar create the div?

**Comment by Will0489** [comment]
This one is relatively old but we were experiencing similar behaviour where the cookiebar would be visible for a split second before it would be hidden. 

I solved this by adding a fade-in transition effect via css (using opacity) on the cookiebar div, which gives the javascript enough time to load and check whether the cookiebar should be shown or not. I think this is a graceful way of resolving this issue.

**Comment by carlwoodhouse** [comment]
Sounds nice :) if you wanted to do a pr I'd be happy to take it, if not
I'll look to apply something similar as soon as I have a minute!

**Comment by dangelion** [comment]
@carlwoodhouse I still have this bug. I'm working on an existing div as cookie bar. In the meantime you could suggest a workaround to solve it?

**Comment by carlwoodhouse** [comment]
display: none; on the div ...

**Comment by carlwoodhouse** [comment]
The resolution for this when using a custom div is to just apply display: none as default.

**Comment by senlin** [comment]
> The resolution for this when using a custom div is to just apply display: none as default.

Doing that simply always hides the cookiebar, I fail to see how this is the right solution?

**Comment by carlwoodhouse** [comment]
@senlin it hides it by default if you do this, but the code will show the bar (clearing the display non) if the user hasn't dismissed the prompt already; if they have dismissed it - it simply stays hidden.

**Comment by senlin** [comment]
ok thanks
