### ISSUE TITLE
bower

### ISSUE THREAD

**Issue by bnomei** [carlwoodhouse/jquery.cookieBar#14]
please request a owner change at bower.
http://bower.io/search/?q=cookiebar
https://github.com/laginha87/jquery.cookieBar
should be you with...
https://github.com/carlwoodhouse/jquery.cookieBar

**Comment by carlwoodhouse** [comment]
happy to do this if i can figure it out! never really used bower

**Comment by carlwoodhouse** [comment]
will get this sorted - seems someone already registered their fork, so will try and get it updated, no idea why but i've not been getting issue notifications for this project :|

**Comment by carlwoodhouse** [comment]
Have added the bower.json and contacted bower to try and get this sorted.

**Comment by carlwoodhouse** [comment]
well bower dont seem to be able to do anything about this arm.
