### ISSUE TITLE
Add git tags

### ISSUE THREAD

**Issue by pvnr0082t** [carlwoodhouse/jquery.cookieBar#15]
Hi @carlwoodhouse ,
Could you please add git tags so that the git auto-updater in [cdnjs](https://github.com/cdnjs/cdnjs) project can recognize the correct version?
Thank you.

https://github.com/cdnjs/cdnjs/issues/7456

**Comment by carlwoodhouse** [comment]
not really used cdnjs before so if you could give me a super quick howto, i'd be glad to do it @pvnr0082t

**Comment by carlwoodhouse** [comment]
super quick skim i presume you just need some kind of tagged release so that has been done. Let me know if it's ok.

**Comment by pvnr0082t** [comment]
@carlwoodhouse Yeah, you got it. Thanks for your big help. :+1:

**Comment by carlwoodhouse** [comment]
No worries :)
