### ISSUE TITLE
Check license

### ISSUE THREAD

**Issue by pvnr0082t** [carlwoodhouse/jquery.cookieBar#16]
Hi @carlwoodhouse ,
https://github.com/carlwoodhouse/jquery.cookieBar/blob/master/jquery.cookieBar.js#L59 said that it's under dual licensed ```MIT``` or ```GPL Version 2```. Is that the license information for dependency or also for this repo? Could you help me confirm it? Thank you.

https://github.com/cdnjs/cdnjs/pull/7825
https://github.com/cdnjs/cdnjs/issues/7456

**Comment by carlwoodhouse** [comment]
The dual license is the dependency, this repo is MIT.

**Comment by pvnr0082t** [comment]
Okay! Thanks a lot.
