### ISSUE TITLE
Adding a CSS class on the cookie bar when accepted

### ISSUE THREAD

**Issue by dangelion** [carlwoodhouse/jquery.cookieBar#20]
I'm using your awesome plugin with a cookie bar in a div created by me.

Problem: When I click the Accept button I need to hide the cookie bar with a "slide down" effect, while now your plugin hide the bar with a display:none.

Is there a way to add a class css on the bar instead of hiding with the display:none ?

**Comment by carlwoodhouse** [comment]
A good way to do this i guess would be to expose an event for this instead which defaults to applying display: none; 

Will look to add this.

**Comment by dangelion** [comment]
Yes, it would be good. Thanks!
