### ISSUE TITLE
Cookie expiration is hard set to 30 days

### ISSUE THREAD

**Issue by raphaelbeckmann** [carlwoodhouse/jquery.cookieBar#26]
This means the cookie bar shows up every 30 days. There should be an option setting.

**Comment by schroef** [comment]
I dont see anything about setting expire date in the documentation. I see its being set to -1, thats quite weird or not? Probably im not understanding the code properly

**Comment by schroef** [comment]
Ow i see, it was a milestone, so seems this project has been abandonded

**Comment by carlwoodhouse** [comment]
Not abandoned just been busy :) sets it as 30 around line 74; would make sense to make it an option that defaults to 30. The -1 is to expire the cookie immediately if that function is called with no options.
