### ISSUE TITLE
Cookie bars without denial feature are not legal in Europe

### ISSUE THREAD

**Issue by elosha** [carlwoodhouse/jquery.cookieBar#31]
I'm currently working on websites that originally use this script. Reason: Customers got pricy caution letters by a lawyer, because the visitor can't deny cookies and third party stuff is always loaded.

This is not legal by EU law and takes the existence of a cookie bar ad absurdum. No offense meant, just wanted to let you know :)

I'm replacing your script now since it doesn't offer the required denial options.

**Comment by carlwoodhouse** [comment]
thanks for the feedback you are right in regards to the eu stuff (though not when the bar was originally created); please note though the 'eu cookiebar' is only a suggested use for the bar and event hooks do exist for the closing the of  the bar; and more could be added easily using the custom content option to fulfil what is required (fair enough if you want to move onto a new script as this isnt really actively maintained!)
